# Generated by Django 4.1 on 2022-08-26 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('nextLevelExp', models.IntegerField(default=100)),
                ('currentExp', models.IntegerField(default=0)),
                ('maxHealth', models.IntegerField(default=0)),
                ('currentHealth', models.IntegerField(default=0)),
                ('maxMana', models.IntegerField(default=0)),
                ('currentMana', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('attack', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('attack', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('attack', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
    ]
